### PR TITLE
WIP: Sound toggle and change timer

### LINKED ISSUE #24: Add option for disabling sound
I have an idea for a simple settings view which would initially just have an "Enable sounds" checkbox (and maybe eventually the ability to set intervals other than 25/5).

### PR DESCRIPTION
**Pull request by laurensiusadi**
Closes #24 and #63 

Slider UI and CSS moved to javascript to allow this changes.
Settings is available via right click menu.
image

The only thing left to be done here is **making all the icons for the new minutes** (up to 60)

### CODE REVIEW

**Comment by laurensiusadi** [comment]
Whoops, I made a mistake changing the electron to version 9, on https://github.com/jasonlong/mater/pull/122/commits/b6cf4633ca470c79baae7c813ee7160adff2c029

Need to work on updating the deps

**Comment by laurensiusadi** [comment]
I didn't do `npm install` when merging new updates, turns out it doesn't work now (the UI messed up), maybe because electron v9? Fixing it now.

**Comment by laurensiusadi** [comment]
The build all good now with `menubar` updated to latest.

**Comment by jasonlong** [comment]
Thanks for working on this @laurensiusadi. 

I'd like to allow people to enter any duration for work and break minutes rather than a couple of presets. My plan is to put this on a new settings panel of some sort which I need to design yet. That's also where the sound toggle will live.

Could we break this PR out into just the sound toggle for now? I think that's a safe feature to add even if it's not the final UI.

**Comment by laurensiusadi** [comment]
Closed in favor of #123

**Pull request closed without merging**
