### PR TITLE
[WIP] Fix Windows icons

### LINKED ISSUE #26: The icon doesn't look great on Windows
untitled
(The reason it has a glow is because my cursor was hovering over it at the time, but the screenshot hides the cursor.)

It looks like the transparent and non-transparent icons are inverted?
**Edit** I see the source images. They look good. But Windows does a bad job of scaling them down further. Perhaps there could be 16x16 icons for Windows?

Thanks for making this.

### PR DESCRIPTION
**Pull request by jasonlong**
(Hopefully eventually) closes #26.

@streeetlamp If you're still up for helping test things, could you pull down this branch and try it on Windows? I've converted just one icon to an `.ico` version – the 0 icon when you first start the app. Could you let me know if it appears white for you rather than black like the current version?

If this approach does the trick, I'll get the rest of the icons converted as well.

### CODE REVIEW

**Comment by jasonlong** [comment]
@ArtskydJ @ankurshva @EanKeen If any of you are comfortable running this branch locally (w/ `npm start`) I'd love to hear if this works for you. I can also make an executable if that's easier.

**Comment by EanKeen** [comment]
@jasonlong I ran the program and the icon appears to be working. However, after a second or two, the icon changed back to how it looked before. Not sure if this is intended behavior.

Initial run
</img>

A few seconds later...
</img>

**Comment by jasonlong** [comment]
Thanks for the feedback @EanKeen. I think I know why the white icon showed and then disappeared. Would you mind pulling the latest and seeing if it's working better now? It *should* work for the duration of the timer (working and breaking).

**Comment by EanKeen** [comment]
Hi,
I also tested this w/ Windows 10 and looks great! I ran the timer through a few times and the icon is consistent.
</img>
 
</img>

**Comment by ArtskydJ** [comment]
Looks like the collapsed toolbar issue is only for Windows 7. (Maybe 8 too, but I don't think so.) This app isn't designed to be collapsed, probably, so I don't see it as being a big deal.

**Comment by jasonlong** [comment]
Thanks for that feedback @ArtskydJ and @EanKeen. I'm not sure about that Windows 7 collapsed toolbar thing and it sounds like it's not an issue with newer versions so I'm not going to worry about it right now. And that web inspector thing is indeed a dev mode thing that's turned on.

I'm going to merge this and create a new release.

**Comment by streeetlamp** [comment]
blah sorry took off yesterday and missed this, good to hear it seems to be working well in windows

**Pull request merged**
